name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: "Create env file"
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Build
        run: npm run build

      - name: Copy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_ADDRESS }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: dist/
          target: /var/www/map.sebastianloose.de/
